### ISSUE TITLE
Intermittently getting Quit inactivity timeout with Node.js 4.2.0

### ISSUE THREAD

**Issue by ratneshdeepak** [felixge/node-mysql#1223]
```
Error: Quit inactivity timeout 
 at Quit.sequence.on.on.on.on.on.self._connection._startTLS.err.code (/var/task/node_modules/mysql/lib/protocol/Protocol.js:154:17) 
 at Quit.emit (events.js:92:17) 
 at Quit._onTimeout (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8) 
 at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```
@dougwilson  I'm using node on aws lambda. The problem is not persistent it reoccurs after every few requests only. 

Here is the test code

```
 var mysql      = require('mysql');
 var mycontext = null;
 var table = "tableName";

if(typeof context === 'undefined'){
 context = {};
 context.fail = function(err){};
 context.succeed = function(o){ console.log("Contect o/p is"); console.log(o);};
 mycontext = context;
}
var processRequest = function (macaddress){
 var connection = null;
	 connection = mysql.createConnection({
	   host  : '*******',
		  user   : '******',
		  password : '*****',
		  database : '******'
	});
	 connection.connect(function(err){
	 if(!err) {
	     console.log("Database is connected ... \n\n");
	 } else {
	     console.log("Error connecting database ... \n\n");
	     handleError(err);
	 }
	 });

 var getConf = function(mac){
  connection.query('SELECT * from '+table+' where macaddress = ? ',[mac], function(err, rows, fields) {
   if (!err){
     console.log('The o/p is: ', rows);
     if(rows.length == 0){
        insertConfig(mac)
     }
     else{
        dispatchConfig(rows[0]);
     }
   }
   else{
     handleError(err);
   }
   });
 };

var insertConfig = function(mac){
 connection.query('INSERT into '+table+' set macaddress = ? ',[mac], function(err, rows, fields) {   
    if(!err){
       console.log('The o/p is: ', rows);
       getConf(mac);
    }
    else
    {
      handleError(err);
    }
 });
}

var dispatchConfig = function(cf){
   connection.end();
   var output = JSON.parse(cf.config);
   output.unshift(["name",cf.id,"i"]);
   mycontext.succeed(JSON.stringify(output));
   
}

var handleError = function(err){
   connection.end();
   mycontext.fail('Something went wrong '+err);
   console.log('Error while performing Query.');
}

getConf(macaddress);

}

exports.handler = function(event, context) {
   mycontext = context;
   processRequest(event.macaddress); 
};
```

**Comment by dougwilson** [comment]
Hi! The error of `Quit inactivity timeout` means one of two things:

1. Something on the network between AWS and your machine is broken. 99% of the time this is reported, it is determined that there is a bad rule on the machine's firewall. The error means that after sending the `Quit` packet to the MySQL server, nothing was never received from the MySQL server in response.
2. Something is going really slow. We wait for 30 seconds after `connection.end();` is called and will throw that error if we don't hear anything back after that long. You can certainly try to increase the timeout, but it's likely that you'll just end up getting that error after a longer time. `connection.end({ timeout: 60000 });`

**Comment by ratneshdeepak** [comment]
Firewall issues can't explain intermittent behavior. Also I've setup mysql
access open from all ip addresses.

Whenever this error occurs exception is thrown within few 100 milliseconds
so 30 seconds timeout is also ruled out.

Can you suggest looking at anything else.

**Comment by dougwilson** [comment]
Interesting. I'll reopen as needs investigation, but I cannot think of anything to look into besides what was listed above. Perhaps there is a bug in this module or in Node.js core (which keeps track of the timeouts)?

I'm not able to reproduce, so without a way to reproduce the issue, there isn't much I can look into successfully. I can poke around at the code here, but it may not ever turn up anything of use. If you could debug your code and determine what is happening and issue up a PR, that's likely the best course of action :)

**Comment by dmtrs** [comment]
Had probably relevant issues like:
```
Error: Query inactivity timeout
      at Query.<anonymous> (node_modules/mysql/lib/protocol/Protocol.js:154:17)
      at Query._onTimeout (node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
      --------------------
      at Pool.query (node_modules/mysql/lib/Pool.js:191:23)
      ....
```
when working with node v4.2.0 and moved to v4.2.1 to resolve it

**Comment by jczaplew** [comment]
I kept getting the same error too, but only with node v4.2.0, and upgrading to v4.2.1 also solved it for me.

**Comment by bahout** [comment]
Hi, more simple, this code was working for me on aws + lambda

```
/*--------------node mysql working example ------*/

var mysql = require('mysql');
var pool = mysql.createPool({
    "host": "captainleads-cluster.cluster-XXCCX.eu-west-1.rds.amazonaws.com",
    "user": "admin",
    "password": "XXXXXX",
    "database": "presta",
    "connectionLimit": 10
});

console.log('Loading function');

exports.handler = function(event, context) {
    pool.query('SELECT * FROM Go_users limit 1', function(err, rows, fields) {
        if (err) {
            throw err;
            context.fail(rows);
        }
        console.log('The solution is: ', rows[0]);

        context.succeed({user:rows[0],msg:'firstuser'});
    });

};
```

**Comment by shreyagarwal** [comment]
Just FYI : Working fine on 4.2.2 and 4.2.3 .. Not working on 4.2.0

**Comment by dougwilson** [comment]
For those still coming across this issue, the bug is fixed. This is from a bug in Node.js 4.2.0 timers. You must upgrade your version of Node.js to actually receive the fix, or use a previous version of Node.js.

If AWS or other platforms only offer Node.js 4.2.0, then you may want to consider using a platform that does not force you to use versions of Node.js with known-fixed bugs.

**Comment by dougwilson** [comment]
I am re-opening this issue if someone wants to take a look into it, since apparently people are still running the issue and claim that upgrading to a version of Node.js that has the bug fix is not possible on AWS.

The only way this issue is going to move forward at this point is if someone wants to provide a pull request with the changes required for this module to work on Node.js 4.2.0. I will not be pursuing a fix, but if someone has a need to run this module on Node.js 4.2.0 and has the time to work on a fix and test it, please contribute.

**Comment by hauboldj** [comment]
I was getting this error running on AWS Lambda running Node4.3. I was able to fix it (e.g. it hasn't happen since I did the fix) by using the new callback feature in AWS Lambda with NodeJs and setting context.callbackWaitsForEmptyEventLoop to true (the default). I believe that the error was caused because when context.done is called Lambda immediately freezes the process. If this happens before the server responds to the `Quit` packet and Lambda unfreezes the process for another function invocation the timeout will be triggered immediately causing this error.

See http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html for more information.

**Comment by jmcazaux** [comment]
I am afraid I am still getting this on AWS with Node 4.3.

I have updated to the last version and it still happens quite frequently actually, but not always.

**Comment by hauboldj** [comment]
@jmcazaux Are you running on EC2 or in AWS Lambda?

**Comment by jmcazaux** [comment]
@hauboldj  AWS Lambda

**Comment by hauboldj** [comment]
Are you using the new callback or context.done/fail/succeed?

**Comment by jmcazaux** [comment]
I am not sure...

I am calling `context.fail("Error message")` and `context.succeed(event)` when it either fails or succeed.

Is it what you mean ?

**Comment by hauboldj** [comment]
Yes. When using node4.3 in AWS Lambda your function handler can have this signature

```
module.exports.handler = function(event, context, callback) {

}
```

The callback is like a regular node call back. callback("Error Message") is the same as context.fail("Error Message") and callback(null, event) is the same as context.succeed(event). However when using the callback AWS Lambda will not freeze the execution until the node event loop is empty. context.done/fail/succeed freeze the execution immediately which I believe causes the problem. The node environment is frozen and does not receive the response. Then the text time the lambda is invoked, the node environment unfreezes and the connection times out immediately.

Try changing to using the callback.

**Comment by jmcazaux** [comment]
I have modified my code.

The first tests seem Ok, thanks @hauboldj.

**Comment by jboddiford** [comment]
I had this same exact issue on AWS Lambda and found that the only way to fix it was to use the callback function. Since making this change, I have had no further errors with MySql!

Thanks everyone for sharing their experience and the fix!
Josh

**Comment by zhangda89** [comment]
i get this error on node version 4.4.7

**Comment by zhangda89** [comment]
i also got this error on node version 4.5.0， only 4.2.0?

**Comment by letakeda** [comment]
I did change the node version but I still see the issue in heroku... any other idea?

```
function oncallDAO(connection){
	this._connection = connection;
}

oncallDAO.prototype.list = function(callback){
	this._connection.query('select * from oncall order by date', callback);
}

oncallDAO.prototype.save = function(oncall, callback){
	this._connection.query('insert into oncall set ?', oncall, callback);
}

oncallDAO.prototype.remove = function(oncall, callback){
	this._connection.query('delete from oncall where id = ?', oncall, callback);
}

module.exports = function(){
	return oncallDAO;
}
```

**Comment by letakeda** [comment]
FYI to who see this page :dancer: 

I changed it to: `connection.end({ timeout: 60000 });` and it worked!

Thanks!

**Comment by jonathanmv** [comment]
I had the same issue but solved it differently. Based on @hauboldj hyphotesis, I used [connection.destroy()](https://github.com/mysqljs/mysql#terminating-connections) instead of connection.end()

> `destroy()` guarantees that no more events or callbacks will be triggered for the connection

**Comment by thiagomarini** [comment]
Using `connection.destroy()` instead of `connection.end()` solved it for me thank god, I had a horrible time with it on AWS lambda running on node 6.

**Comment by jordie23** [comment]
I'd just like to say that we had this problem and it was fixed by just using the callback function of `connection.end`. So using the original post's code, this is how that would change:

```
var dispatchConfig = function(cf){
   connection.end(() => {
      var output = JSON.parse(cf.config);
      output.unshift(["name",cf.id,"i"]);
      mycontext.succeed(JSON.stringify(output));
   });
}

var handleError = function(err){
   console.log('Error while performing Query.');
   connection.end(() => {
      mycontext.fail('Something went wrong '+err);
   });
}
```

**Comment by gvorster** [comment]
I'm using node 8.10 and express on AWS Lambda and connection.destroy() solved this for me too.
